edgexfoundry/docker-edgex-mongo

Dockerfile, launch-edgex-mongo.sh
With this change docker-edgex-mongo-seed is no longer needed as the init_mongo.js is executed some seconds after the docker is started.
This change needs a change to docker-compose.yml that is in a different pull request in developer-scripts.
=> Run init_mongo.js every time the docker is started

.gitignore, init_mongo.js
#12 
Adding support in the init_mongo.js for the scheduler mongo db. 
This includes adding support script for permissions and index(s) for the scheduler db.
- added a .gitignore file to suppress accidental addition of project files, vendor files etc..
Signed-off-by: xmlviking <ecotter@gmail.com>
=> adding support for the scheduler service, adding gitignore file

init_mongo.js
Change #16 
This places the index in the mongo support-scheduler DB on "name" and not "slug"
Signed-off-by: xmlviking <ecotter@gmail.com>
=> updating init_mongo.js support-scheduler index on name not slug

init_mongo.js
Fix #19
Related to: EdgeX-GO #1286
Add an index to the reading collection for the device field which will
allow for more effective deletions when deleting all readings associated
with a specific device. This will prevent the database manager from
performing a full scan.
Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>
=> Add index to Mongo for Reading's device field

init_mongo.js
Fix #26
Adding missing lines for export-client sourced from https://github.com/edgexfoundry/developer-scripts/blob/master/init_mongo.js
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
=> Adding export-client db/collection/user

bin/edgex-mongo-launch.sh
Remove the re-try loop from the bash file
and stay with the already existing retry mechanism for getting database session. 
The BootTimeout is configurable. The default value is up to 30 seconds.
Fix: https://github.com/edgexfoundry/docker-edgex-mongo/issues/36
=> Remove the re-try loop from the bash file

bin/edgex-mongo-launch.sh, cmd/Dockerfile
Because of Snyk reports lots of Common vulnerabilities and exposures
the docker-edgex-mongo start using instead of mongo:4.0-xenial, but mongo:4.2.0-bionic.
Flag '--smallfiles' not available anymore.
Fix: https://github.com/edgexfoundry/docker-edgex-mongo/issues/43
=> Upgrade Mongo image to mongo:4.2.0-bionic

cmd/res/configuration.toml, cmd/res/docker/configuration.toml, go.mod, internal/pkg/config.go, internal/secure/config.go
Update docker-edgex-mongo to reflect the changes done by PR edgexfoundry/go-mod-secrets#31 , issue edgexfoundry/go-mod-secrets#26
The SecretConfig struct retains its Path variable, that provides the base searching path for vault, meanwhile the SecretClient interface changed its signature to
GetSecrets(path string, keys ...string) (map[string]string, error)
This path, if provided, will be attached to the base searching path - thus each microservice will be able to read secrets from different paths (under their base search path)
renamed: RootCaCert - to RootCaCertPath
path updated to /v1/secret/edgex/mongo
update go.mod file
Fix: https://github.com/edgexfoundry/docker-edgex-mongo/pull/51
=> Reflect changes done in SecretClient interface

cmd/res/configuration.toml, cmd/res/docker/configuration.toml, internal/client.go, internal/pkg/config.go, internal/secure/config.go
- "Rule_engine_db" databases come "ruleengine"
- application-service database Username become "appservice"
- get databases names from the config file
- renaming in toml file: "Credentials" replaced with "Databases"
https://github.com/edgexfoundry/edgex-go/issues/1891
=> Keep database names consistent

cmd/Dockerfile
Remove EDGEX_SECURITY_SECRET_STORE env variable from the Docker file,
thus work in security mode by default
=> Start working in Security enabled mode by default

cmd/Dockerfile
We need this to do dependency checking to ensure that docker-edgex-mongo isn't started until after security-secretstore-setup finishes running. 
the associated change in docker-compose is in my developer-scripts PR here: https://github.com/edgexfoundry/developer-scripts/pull/172
Partially resolves https://github.com/edgexfoundry/developer-scripts/issues/167
=> Dockerfile: add curl to the base image

cmd/Dockerfile.aarch64
Run mongo container as root, because otherwise it does not have permissions
to read secrets from Vault
=> Run mongo container as root

cmd/res/configuration.toml, cmd/res/docker/configuration.toml, go.mod, internal/pkg/config.go, internal/secure/config.go
This will fix the race condition we currently have when security-secretstore-setup is run at the same time as docker-edgex-mongo and the secrets haven't been put into vault yet and currently docker-edgex-mongo immediately fails when vault returns a 404 for the secret.
This depends on https://github.com/edgexfoundry/go-mod-secrets/pull/36.
To test this, I pushed the above go-mod-secrets change to master at my fork, so if you add the following to your go.mod:
```
replace github.com/edgexfoundry/go-mod-secrets => github.com/anonymouse64/go-mod-secrets v0.0.8-0.20191105235208-65a79df9754e
```
then you should be able to build this. To test it, build the docker container here with:
```
$ make docker
```
and checkout master branch of developer-scripts and follow all the testing instructions for …
=> internal/secure/config.go: specify 10 retry attempts @ 1 Hz

cmd/Dockerfile.aarch64
Removed environment vars from ARM64 Dockerfile that were disabling
security.
Fix #63
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
=> Enable ARM64 Security

.gitignore, go.mod, internal/secure/config.go
This is meant in conjunction with https://github.com/edgexfoundry/go-mod-secrets/pull/38, where go-mod-secrets will do the parsing of the time, so that clients of go-mod-secrets just take in simple values and go-mod-secrets figures out what to do with them.
To test this locally, I pushed my go-mod-secrets branch to my fork, so you can replace go-mod-secrets in go.mod like so:
```patch
diff --git a/go.mod b/go.mod
index 09b031a..2d44366 100644
--- a/go.mod
+++ b/go.mod
@@ -10,4 +10,6 @@ require (
gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15 // indirect
)
+replace github.com/edgexfoundry/go-mod-secrets => github.com/anonymouse64/go-mod-secrets master
+
go 1.12
```
The tests here will fail until the go-mod-secrets PR is merged and the merge job runs which tags the commit. After a new …
=> internal/secure/config.go: provide RetryWaitPeriod as string

.gitignore, cmd/res/configuration.toml, cmd/res/docker/configuration.toml, go.mod, internal/pkg/config.go, internal/secure/config.go
This is a duplicate of https://github.com/edgexfoundry/docker-edgex-mongo/pull/59 and https://github.com/edgexfoundry/docker-edgex-mongo/pull/67 combined into one PR for master/Geneva.
=> internal/secure/config.go: specify 10 retry attempts @ 1 Hz (master)

cmd/res/docker/configuration.toml
The CA TLS path is changed due to the change of issue #1716 on TLS path changes.
Related to fixing [edgex-go issue #1716](https://github.com/edgexfoundry/edgex-go/issues/1716), on step 2 of PR [edgexfoundry#2146](https://github.com/edgexfoundry/edgex-go/pull/2146)
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>
=> Update CA TLS path for docker environment

bin/edgex-mongo-launch.sh
Mongo DB is started firstly bound to localhost, then all users, databases and collection are initialized,
and finally mongo db is restarted with enabled access control and --bind_ip_all
Fix: https://github.com/edgexfoundry/docker-edgex-mongo/issues/77
Note: When database credentials are not generated on every restart of the system, a follow up issue could be opened, that so that the logic inside edgex-mongo and the restart of mongo itself to happen only on the first start . 
=> Start mongo with enabled access control

bin/edgex-mongo-launch.sh, cmd/Dockerfile
Use dumb-init and keep image size small
Fix: https://github.com/edgexfoundry/docker-edgex-mongo/issues/37
=> Use dumb-init and keep image size small 

cmd/Dockerfile
Snyk reporting as many as CVE's with older versions of base images
so upgrading to latest available to fix some of them
Signed-off-by: Koppolu <venkata.subbareddy.koppolu@intel.com>
=> Upgrade for Mongo base image to mongo:4.2.3-bionic

bin/edgex-mongo-launch.sh
If `/tmp/edgex/secrets/edgex-mongo/.mongo-database-setup-done` does not exist
run mongo database bind to localhost and re-provision all db collections and credentials
else - immediately run mongo database with enabled authentication
Fix: https://github.com/edgexfoundry/docker-edgex-mongo/issues/85
=> Do not provision db credential on each restart
